CREATE TABLE IF NOT EXISTS `#__address_node` (
  `adid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uid` int(10) unsigned NOT NULL,
  `address1` varchar(100) NOT NULL,
  `address2` varchar(100) NOT NULL,
  `address3` varchar(100) NOT NULL,
  `city` varchar(40) NOT NULL,
  `state` varchar(40) NOT NULL,
  `zipcode` varchar(25) NOT NULL,
  `ctyid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `alias` varchar(150) NOT NULL,
  `publish` tinyint(4) NOT NULL DEFAULT '1',
  `name` varchar(255) NOT NULL DEFAULT 'default',
  `stateid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `created` int(10) unsigned NOT NULL DEFAULT '0',
  `modified` int(10) unsigned NOT NULL DEFAULT '0',
  `vendid` int(10) unsigned NOT NULL DEFAULT '0',
  `premium` tinyint(4) NOT NULL DEFAULT '0',
  `type` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `business` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `phone` varchar(20) NOT NULL,
  `params` text NOT NULL,
  `latitude` double(12,8) NOT NULL DEFAULT '222.00000000',
  `longitude` double(12,8) NOT NULL DEFAULT '222.00000000',
  `location` varchar(255) NOT NULL,
  `found` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `lastcheck` int(10) unsigned NOT NULL DEFAULT '0',
  `mapservice` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `usercreate` tinyint(3) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`adid`),
  KEY `IX_address_node_location` (`location`),
  KEY `IX_address_node_uid` (`uid`)
) ENGINE=InnoDB   /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci*/;