CREATE TABLE IF NOT EXISTS `#__project_node` (
  `pjid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `namekey` varchar(100) NOT NULL,
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `lft` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `rgt` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `parent` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `rolid` smallint(5) unsigned NOT NULL DEFAULT '7',
  `ordering` tinyint(3) unsigned NOT NULL DEFAULT '99',
  `publish` tinyint(4) NOT NULL DEFAULT '1',
  `modified` int(10) unsigned NOT NULL DEFAULT '0',
  `created` int(10) unsigned NOT NULL DEFAULT '0',
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `startdate` int(10) unsigned NOT NULL DEFAULT '0',
  `enddate` int(10) unsigned NOT NULL DEFAULT '0',
  `priority` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `author` int(10) unsigned NOT NULL DEFAULT '0',
  `estimatedtime` int(10) unsigned NOT NULL DEFAULT '0',
  `depth` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `frontend` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ltkid` int(10) unsigned NOT NULL DEFAULT '0',
  `tickets` smallint(5) unsigned NOT NULL DEFAULT '0',
  `oncreation` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `onreplies` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `toassigned` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `sendcopy` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `group` tinyint(3) unsigned NOT NULL DEFAULT '5',
  `email` varchar(100) NOT NULL,
  PRIMARY KEY (`pjid`)
) ENGINE=InnoDB   /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci*/;