CREATE TABLE IF NOT EXISTS `#__ticket_node` (
  `tkid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tktypeid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `status` tinyint(4) NOT NULL DEFAULT '20',
  `deadline` int(10) unsigned NOT NULL DEFAULT '4200000003',
  `assigned` int(10) unsigned NOT NULL,
  `created` int(10) unsigned NOT NULL DEFAULT '0',
  `modified` int(10) unsigned NOT NULL DEFAULT '0',
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `priority` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `namekey` varchar(100) NOT NULL,
  `ordering` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `authoruid` int(10) unsigned NOT NULL DEFAULT '0',
  `stid` int(10) unsigned NOT NULL DEFAULT '0',
  `pjid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `private` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `resptime` tinyint(3) unsigned NOT NULL DEFAULT '10',
  `assignuid` int(10) unsigned NOT NULL DEFAULT '0',
  `rolid` smallint(5) unsigned NOT NULL DEFAULT '1',
  `replies` smallint(5) unsigned NOT NULL DEFAULT '0',
  `timing` smallint(5) unsigned NOT NULL DEFAULT '0',
  `wordcount` smallint(5) unsigned NOT NULL DEFAULT '0',
  `charcount` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `elapsed` int(10) unsigned NOT NULL DEFAULT '0',
  `sticky` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `lock` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `score` int(10) unsigned NOT NULL DEFAULT '0',
  `votes` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `etid` int(10) unsigned NOT NULL DEFAULT '0',
  `useful` int(10) unsigned NOT NULL DEFAULT '0',
  `usefulclick` int(10) unsigned NOT NULL DEFAULT '0',
  `commenttype` smallint(5) unsigned NOT NULL DEFAULT '0',
  `usefulrate` int(10) unsigned NOT NULL DEFAULT '0',
  `ip` double unsigned DEFAULT '0',
  `comment` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `followup` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `assignbyuid` int(10) unsigned NOT NULL DEFAULT '0',
  `publish` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `read` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `latereply` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `lcid` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`tkid`),
  KEY `IX_ticket_node_authoruid` (`authoruid`),
  KEY `IX_ticket_node_pjid` (`pjid`),
  KEY `IX_ticket_node_modified` (`modified`)
) ENGINE=InnoDB   /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci*/;