CREATE TABLE IF NOT EXISTS `#__product_node` (
  `pid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `price` decimal(15,4) unsigned NOT NULL DEFAULT '0.0000',
  `curid` smallint(5) unsigned NOT NULL DEFAULT '1',
  `created` int(10) unsigned NOT NULL DEFAULT '0',
  `modified` int(10) unsigned NOT NULL DEFAULT '0',
  `availablestart` int(10) unsigned NOT NULL DEFAULT '0',
  `publish` tinyint(4) NOT NULL DEFAULT '0',
  `weight` decimal(10,4) unsigned NOT NULL DEFAULT '0.0000',
  `filid` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `prodtypid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `namekey` varchar(150) NOT NULL,
  `stock` mediumint(9) NOT NULL DEFAULT '-1',
  `rolid` smallint(5) unsigned NOT NULL DEFAULT '1',
  `numcat` smallint(5) unsigned NOT NULL DEFAULT '0',
  `publishstart` int(10) unsigned NOT NULL DEFAULT '0',
  `publishend` int(10) unsigned NOT NULL DEFAULT '0',
  `bundle` smallint(5) unsigned NOT NULL DEFAULT '0',
  `comment` tinyint(4) NOT NULL DEFAULT '1',
  `numdiscount` smallint(5) unsigned NOT NULL DEFAULT '0',
  `vendid` int(10) unsigned NOT NULL DEFAULT '1',
  `lsid` varchar(255) NOT NULL DEFAULT '',
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `nbreviews` int(11) NOT NULL DEFAULT '0',
  `score` int(11) NOT NULL DEFAULT '0',
  `votes` int(11) NOT NULL DEFAULT '0',
  `payment` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `priceid` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `useraffle` tinyint(4) NOT NULL DEFAULT '0',
  `unitid` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `featured` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `nbsold` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `author` int(10) unsigned NOT NULL DEFAULT '0',
  `relnum` smallint(5) unsigned NOT NULL DEFAULT '0',
  `electronic` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `alias` varchar(255) NOT NULL DEFAULT '',
  `availableend` int(10) unsigned NOT NULL DEFAULT '0',
  `previewid` int(10) unsigned NOT NULL DEFAULT '0',
  `cssclass` varchar(100) NOT NULL DEFAULT '',
  `params` text NOT NULL,
  `blocked` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `resell` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `target` int(10) unsigned NOT NULL DEFAULT '0',
  `targettotal` int(10) unsigned NOT NULL DEFAULT '0',
  `adid` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `rolid_buy` int(10) unsigned NOT NULL DEFAULT '0',
  `discountrate` double(5,2) unsigned NOT NULL DEFAULT '0.00',
  `discountvalue` decimal(15,4) unsigned NOT NULL DEFAULT '0.0000',
  `migid` smallint(5) unsigned NOT NULL DEFAULT '1',
  `migrefid` int(10) unsigned NOT NULL DEFAULT '0',
  `location` varchar(254) NOT NULL,
  `longitude` double(12,8) NOT NULL DEFAULT '222.00000000',
  `latitude` double(12,8) NOT NULL DEFAULT '222.00000000',
  `featuredate` int(10) unsigned NOT NULL DEFAULT '0',
  `color` varchar(100) NOT NULL,
  `length` int(10) unsigned NOT NULL DEFAULT '0',
  `width` int(10) unsigned NOT NULL DEFAULT '0',
  `height` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`pid`),
  UNIQUE KEY `UK_product_node_namekey` (`namekey`),
  KEY `IX_product_node_publish_prodtypid` (`publish`,`prodtypid`),
  KEY `IX_product_node_vendid` (`vendid`),
  KEY `IX_product_node_longitute_latitude` (`latitude`,`longitude`),
  KEY `IX_product_node_priceid` (`priceid`)
) ENGINE=InnoDB   /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci*/;