CREATE TABLE IF NOT EXISTS `#__productcat_node` (
  `catid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `filid` int(10) unsigned NOT NULL DEFAULT '0',
  `namekey` varchar(100) NOT NULL,
  `alias` varchar(150) NOT NULL,
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `rgt` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `lft` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `parent` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `rolid` smallint(5) unsigned NOT NULL DEFAULT '1',
  `ordering` int(10) unsigned NOT NULL DEFAULT '0',
  `publish` tinyint(4) NOT NULL DEFAULT '0',
  `modified` int(10) unsigned NOT NULL DEFAULT '0',
  `created` int(10) unsigned NOT NULL DEFAULT '0',
  `author` int(10) unsigned NOT NULL DEFAULT '0',
  `params` text NOT NULL,
  `depth` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `numpid` int(10) unsigned NOT NULL DEFAULT '0',
  `vendid` int(10) unsigned NOT NULL DEFAULT '1',
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `publishstart` int(10) unsigned NOT NULL DEFAULT '0',
  `publishend` int(10) unsigned NOT NULL DEFAULT '0',
  `cssclass` varchar(100) NOT NULL,
  `prodtypid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `layout` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `blocked` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `featured` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`catid`),
  UNIQUE KEY `IX_objectName_cat_namekey` (`namekey`)
) ENGINE=InnoDB   /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci*/;