CREATE TABLE IF NOT EXISTS `#__featured_node` (
  `ftdid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `namekey` varchar(150) NOT NULL,
  `alias` varchar(150) NOT NULL,
  `type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `rolid` smallint(5) unsigned NOT NULL DEFAULT '1',
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `publish` tinyint(4) NOT NULL DEFAULT '0',
  `created` int(10) unsigned NOT NULL DEFAULT '0',
  `modified` int(10) unsigned NOT NULL DEFAULT '0',
  `location` varchar(50) NOT NULL,
  `featured` tinyint(3) unsigned NOT NULL DEFAULT '1',
  `badge` varchar(50) NOT NULL,
  `background` varchar(20) NOT NULL,
  `cssstyle` text NOT NULL,
  `credits` double(7,2) NOT NULL DEFAULT '0.00',
  `duration` int(10) unsigned NOT NULL DEFAULT '0',
  `bordercolor` varchar(20) NOT NULL,
  `ordering` smallint(5) unsigned NOT NULL DEFAULT '0',
  `badgecolor` varchar(20) NOT NULL,
  `cssclass` varchar(50) NOT NULL,
  `badgeposition` varchar(20) NOT NULL,
  PRIMARY KEY (`ftdid`),
  UNIQUE KEY `UK_namekey_jos_featured_node` (`namekey`),
  KEY `ix_featured_node_location` (`location`)
) ENGINE=InnoDB   /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci*/;